### ISSUE TITLE
Request: use .js instead of .jsx

### ISSUE THREAD

**Issue by austinmao** [jrowny/react-absolute-grid#18]
Using .js as a file extension will make this easier to consume as a library for those of us that don't have jsx in a webpack loader :)

**Comment by okonet** [comment]
A agree on the extension but you should not consume source files since this library exports a es5 compatible source with all drops included.

**Comment by okonet** [comment]
Even if you still want to compile it yourself, you don't need jsx-loader but babel-loader instead

**Comment by austinmao** [comment]
Thanks for the reply. The index.js from a npm install references

```
module.exports = require('./lib/AbsoluteGrid.jsx');
```

I really want to use this lib but I am having trouble figuring out how to get babel-loader to work with the boilerplate I'm using. See: https://github.com/erikras/react-redux-universal-hot-example/issues/670

**Comment by austinmao** [comment]
I have the jsx loader working but now I'm getting this:

```
[0] ./~/react-absolute-grid/lib/AbsoluteGrid.jsx
[0] Module build failed: TypeError: The plugin "lodash" didn't export a Plugin instance
[0]     at PluginManager.validate (/Users/austinmao/Sites/aditive-frontend/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
[0]     at PluginManager.add (/Users/austinmao/Sites/aditive-frontend/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
[0]     at File.buildTransformers (/Users/austinmao/Sites/aditive-frontend/node_modules/babel-core/lib/transformation/file/index.js:237:21)
[0]     at new File (/Users/austinmao/Sites/aditive-frontend/node_modules/babel-core/lib/transformation/file/index.js:139:10)
[0]     at Pipeline.transform (/Users/austinmao/Sites/aditive-frontend/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
[0]     at transpile (/Users/austinmao/Sites/aditive-frontend/node_modules/babel-loader/index.js:12:22)
[0]     at Object.module.exports (/Users/austinmao/Sites/aditive-frontend/node_modules/babel-loader/index.js:69:12)
[0]  @ ./~/react-absolute-grid/index.js 1:17-50
[0] webpack built 05cae59ad569e0bf7e70 in 33409ms
```

From this issue, it would seem to be affecting people on a babel version pre 6.0: https://github.com/megawac/babel-plugin-lodash/issues/7

Please let me know if there is a way I can access an es5 compatible source via npm. Thanks!

**Comment by okonet** [comment]
It should be compiled when installed via npm. Did you get this error with an npm version? This doesn't make sense to me

**Comment by austinmao** [comment]
I think it's a clash between the https://github.com/megawac/babel-plugin-lodash that you are using and the one that I am using that comes with the https://github.com/erikras/react-redux-universal-hot-example boilerplate. I manually did a `npm build` on your library and required it that way. I'm not really sure how to fix this.

**Comment by okonet** [comment]
You should not manually build this library. You should install it via npm.

**Comment by okonet** [comment]
If you want to build manually I think I can't help you resolving version conflicts.

**Comment by austinmao** [comment]
I have tried installing it via npm in both my codebase and the default https://github.com/erikras/react-redux-universal-hot-example boilerplate. In both cases, when I import AbsoluteGrid, I get the error I pasted at the top of this issue. :(

I only manually built it because I really want to use your incredible library.

**Comment by okonet** [comment]
What version did you install? The build process has been changed in the 2.x. Please be aware that it has breaking changes.

**Comment by austinmao** [comment]
Version 2.0.0. I tried it today and tried to troubleshoot this for a good hour or so.

**Comment by okonet** [comment]
Let me check. I see something strange.

**Comment by austinmao** [comment]
Thank you sir!

**Comment by gbmhunter** [comment]
+1

**Comment by okonet** [comment]
Fixed in 6f099419799cb3240fad66648e45d402f8f05af8

**Comment by austinmao** [comment]
Thanks!

**Comment by gbmhunter** [comment]
Cheers @okonet .
